# Generated by Django 4.0.3 on 2022-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone_number', models.CharField(max_length=200)),
                ('grooming_package', models.CharField(max_length=200)),
                ('grooming_session', models.DateTimeField(verbose_name='Date Booking and Time')),

            ],
        ),
    ]
